#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 17, 2021 09:09:55 AM MST  platform: Linux

import sys
from cryptography.fernet import Fernet

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import smtpsettings_support

def savesettings(server, port, sender, password, recip):
    #generate encryption key
    sender = sender.get()
    password = password.get()
    recip = recip.get()
    port = port.get()
    server = server.get()
    key = Fernet.generate_key()
    fernet = Fernet(key)
    encryptedsender = fernet.encrypt(sender.encode())
    encryptedpassword = fernet.encrypt(password.encode())
    encryptedrecip = fernet.encrypt(recip.encode())
    
    f = open("src/config.txt", "w")
    f.write(str(server+"\n"+port+"\n"+encryptedsender.decode("utf-8")+"\n"+encryptedpassword.decode("utf-8")+"\n"+encryptedrecip.decode("utf-8")))

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    smtpsettings_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    smtpsettings_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("360x360+297+289")
        top.minsize(1, 1)
        top.maxsize(3185, 1250)
        top.resizable(1,  1)
        top.title("Settings")
        top.configure(background="#474747")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.028, relheight=0.842, relwidth=0.981)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#2d2d2d")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.028, rely=0.026, height=23, width=179)
        self.Label1.configure(background="#2d2d2d")
        self.Label1.configure(font="-family {DejaVu Sans} -size 14 -weight bold")
        self.Label1.configure(text='''SMTP Settings''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.057, rely=0.086, height=14, width=90)
        self.Label2.configure(background="#2d2d2d")
        self.Label2.configure(text='''G-Mail Only''')

        self.serverLabel = tk.Label(self.Frame1)
        self.serverLabel.place(relx=0.028, rely=0.271, height=14, width=109)
        self.serverLabel.configure(background="#2d2d2d")
        self.serverLabel.configure(text='''SMTP Server:''')

        server = tk.StringVar()
        self.server = tk.StringVar(self.Frame1)
        self.Entry1 = tk.Entry(self.Frame1, textvariable=self.server)
        self.Entry1.place(relx=0.337, rely=0.271, height=23, relwidth=0.385)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.saveButton = tk.Button(self.Frame1)
        self.saveButton.place(relx=0.816, rely=0.894, height=23, width=53)
        self.saveButton.configure(background="#4c4c4c")
        self.saveButton.configure(borderwidth="2")
        self.saveButton.configure(text='''Save''', command=lambda: savesettings(self.server, self.port, self.sender, self.password, self.recip))

        self.portLabel = tk.Label(self.Frame1)
        self.portLabel.place(relx=0.028, rely=0.356, height=15, width=50)
        self.portLabel.configure(background="#2d2d2d")
        self.portLabel.configure(text='''Port:''')

        port = tk.StringVar()
        self.port = tk.StringVar(self.Frame1)
        self.Entry2 = tk.Entry(self.Frame1, textvariable=self.port)
        self.Entry2.place(relx=0.17, rely=0.356, height=23, relwidth=0.13)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.senderLabel = tk.Label(self.Frame1)
        self.senderLabel.place(relx=0.057, rely=0.462, height=15, width=100)
        self.senderLabel.configure(background="#2d2d2d")
        self.senderLabel.configure(text='''Sender E-Mail:''')

        sender = tk.StringVar()
        self.sender = tk.StringVar(self.Frame1)
        self.Entry3 = tk.Entry(self.Frame1, textvariable=self.sender)
        self.Entry3.place(relx=0.365, rely=0.449, height=23, relwidth=0.385)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkFixedFont")

        password = tk.StringVar()
        self.password = tk.StringVar(self.Frame1)
        self.Entry4 = tk.Entry(self.Frame1, textvariable=self.password)
        self.Entry4.place(relx=0.283, rely=0.538, height=23, relwidth=0.244)
        self.Entry4.configure(background="white")
        self.Entry4.configure(font="TkFixedFont")

        self.passwordLabel = tk.Label(self.Frame1)
        self.passwordLabel.place(relx=0.028, rely=0.561, height=15, width=79)
        self.passwordLabel.configure(background="#2d2d2d")
        self.passwordLabel.configure(text='''Password:''')

        self.descLabel = tk.Label(self.Frame1)
        self.descLabel.place(relx=0.028, rely=0.746, height=15, width=169)
        self.descLabel.configure(background="#2d2d2d")
        self.descLabel.configure(text='''E-Mail to send alerts to:''')

        recip = tk.StringVar()
        self.recip = tk.StringVar(self.Frame1)
        self.Entry5 = tk.Entry(self.Frame1, textvariable=self.recip)
        self.Entry5.place(relx=0.535, rely=0.746, height=23, relwidth=0.442)
        self.Entry5.configure(background="white")
        self.Entry5.configure(font="TkFixedFont")

if __name__ == '__main__':
    vp_start_gui()





